---
title: "fig study area"
author: "Louis Schroll"
date: "2024-05-20"
output: html_document
---

```{r}
library(tidyverse)
library(sf)
library(terra)
library(osmdata)
library(elevatr)
library(ggspatial)
library(ggrepel)
library(leaflet)
library(plotly)


area <- st_crop(
  gdlmap %>% select(geometry, NAME),
  xmin = 640000,
  ymin = 6115601,
  xmax = 930000,
  ymax = 6350000
)

plot(area)

gdl_elev_raster <- get_elev_raster(locations = area,
                                  z = 12,
                                  clip = "locations",
                                  src="aws"
) %>%
  rast() %>%
  # ramener les valeurs négatives à zéro
  app(fun=function(x){ x[x < 0] <- 0; return(x)}) %>% 
  aggregate(fact=20)

# gdl_ombr_raster <- shade(terrain(gdl_elev_raster, v='slope')/180*pi,
#                         terrain(gdl_elev_raster, v='aspect')/180*pi,
#                         angle=40, direction=330
# )

# plot(gdl_ombr_raster, col=grey(0:100/100))

#gdl_ombr_raster_2 <- aggregate(gdl_ombr_raster, fact=2)

ggplot() +
  layer_spatial(gdl_elev_raster) +
  scale_fill_gradientn(colors=terrain.colors(n=40), na.value = 0) +
  theme_bw()

writeRaster(gdl_elev_raster, 
            file = "~/stage_M2/1.data/elevation_gdl_raster.tif", 
            overwrite=TRUE)

library(RJSONIO)
locateCountry = function(nameCity, codeCountry) {
  cleanCityName = gsub(' ', '%20', nameCity)
  url = paste(
    "http://nominatim.openstreetmap.org/search?city="
    , cleanCityName
    , "&countrycodes="
    , codeCountry
    , "&limit=9&format=json"
    , sep="")
  resOSM = fromJSON(url)
  if(length(resOSM) > 0) {
    return(c(resOSM[[1]]$lon, resOSM[[1]]$lat))
  } else return(rep(NA,2)) 
}

cities = data.frame(nom=c("Montpellier", "Perpignan", "Narbonne", "Marseille"), pays=rep("FR",4))
print(cities)
coord = t(apply(cities, 1, function(aRow) locateCountry(aRow[1], aRow[2])))
cities_sf <- as_tibble(coord) %>% 
  rename(lat = V1, lon = V2) %>% 
  bind_cols(cities) %>% 
  st_as_sf(coords = c("lat", "lon")) %>% 
  st_set_crs(value=st_crs(depth_raster)) %>% 
  st_transform(crs = st_crs(area))

```

```{r}
city_names <- bind_cols(st_drop_geometry(cities_sf),
                        st_coordinates(cities_sf)) %>%
  mutate(Y = case_when(nom == "Narbonne" ~ Y - 0.06,
            TRUE ~ Y + 0.07))
# 
# lion_gulf_plot <- ggplot() + 
#   geom_sf(data = grid2, lwd = 0.1, fill = NA) +
#   geom_sf(data = area, fill= "antiquewhite") +
#   # select an area
#   # add scale (ggspatial package)
#   annotation_scale(location = "br", width_hint = 0.3,
#                    height = unit(0.15, "cm")) +
#   # add noth arrow (ggspatial package)
#   annotation_north_arrow(location = "tr", which_north = "true", 
#                          pad_x = unit(0.25, "cm"), pad_y = unit(0.4, "cm"),
#                          style = north_arrow_fancy_orienteering,
#                          height = unit(1, "cm"),
#                          width = unit(1, "cm")) + 
#   annotate(geom = "text", x = 4.5, y = 42.7, label = "Gulf of Lion", 
#            fontface = "italic", color = "grey22", size = 6) +
#   theme(panel.background = element_rect(fill = "aliceblue"),
#         panel.grid = element_blank(),
#         axis.title = element_blank(),
#         axis.text = element_text(size = 5.5)) +
#   geom_sf(data = cities_sf)

library(ggnewscale)
library(tmap)

local_path <- "~/stage_M2/"
# Load grid
load("~/stage_M2/1.data/grid.rdata")
load("~/stage_M2/1.data/gdlmap.Rdata")
load(file = paste0(local_path, "1.data/wind_farm_boundaries2.RData")) # wind farm

# Load depth layer
depth_raster <- rast(paste0(local_path, "1.data/static_covariates_raster.tif"))
load(file = "~/stage_M2/1.data/elevation_gdl_raster.RData")
plot(depth_raster$bathymetry)

crs(depth_raster)
depth_raster2 <- project(depth_raster, y = crs(gdlmap)) %>% 
  crop(gdl_elev_raster)
depth_tibble <- crds(depth_raster2) %>% bind_cols(as_tibble(depth_raster2))

crs(gdl_elev_raster) <- crs(gdlmap)
altitude_tibble <- crds(gdl_elev_raster) %>% bind_cols(as_tibble(gdl_elev_raster))

# Make the plot
study_area <- grid %>% st_union()
wind_farm_color <- c("brown", "darkgreen")

library(extrafont)

ggplot() +
  geom_raster(data = depth_tibble, aes(x = x, y = y, fill = bathymetry)) +
  scale_fill_distiller(guide = guide_colourbar(
        title = "Bathymetry",
        title.theme = element_text(
          size = 8, 
          face = "bold",
          family = "rubik",
          hjust = 0.5),
        title.position = 'top',
        title.hjust = 0,
        ticks = FALSE,
        barwidth = unit(6, 'lines'),
        barheight = unit(0.4, 'lines'),
        label.theme = element_text(size = 6))) +
  new_scale_fill() +
  geom_sf(data = wind_farm, 
            aes(col = as.factor(zone_type), fill = as.factor(zone_type)),
          alpha = 0.1) +
  geom_sf_text(data = wind_farm, aes(label = zone_nb, col = as.factor(zone_type)), size = 3) +
  scale_color_manual(values = wind_farm_color, guide = FALSE) +
  scale_fill_manual(values = wind_farm_color, name = "Wind farm zones",
                    guide = guide_legend(title.position = 'top',
                                         nrow = 2, byrow = TRUE,
                                         title.theme = element_text(
                                           size = 8, 
                                           face = "bold"))) +
  geom_sf(data = study_area, lwd = 0.1, fill = NA) +
  new_scale_fill() +
  layer_spatial(gdl_elev_raster) +
  scale_fill_gradientn(colors = terrain.colors(n = 40), 
                       na.value = 0,
                       guide = FALSE) +
  geom_sf_text(data = cities_sf, aes(label = nom), size = 3) +
  # geom_text(data=city_names,
  #           aes(x=X, y=Y, label = nom),
  #           color = "black",
  #           fontface = "bold",
  #           check_overlap = T,
  #           size = 2) +
  annotation_scale(location = "br", 
                   pad_y = unit(0.6, "cm"),
                   pad_x = unit(0.8, "cm"),
                   width_hint = 0.3,
                   height = unit(0.15, "cm")) +
  annotation_north_arrow(location = "tr", which_north = "true", 
                         pad_x = unit(0.5, "cm"), 
                         pad_y = unit(0.8, "cm"),
                         style = north_arrow_fancy_orienteering,
                         height = unit(1, "cm"),
                         width = unit(1, "cm")) + 
  annotate(geom = "text", x = 820000, y = 6180000, label = "Gulf of Lion", 
           fontface = "italic", color = "grey22", size = 6) +
  theme_classic() +
  theme(legend.position = "bottom",
        legend.box = "horizontal",
        legend.justification = 0.2,
        legend.box.spacing = unit(0, "cm"),
        axis.title = element_blank(),
        axis.line = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank())

lion_gulf_plot



 # c("Leelawadee", "Verdana", "Tw Cen MT", Trebuchet MS, Times New Roman, Rockwell,
 # "Gadugi", "Calibri", "Cambria", "Georgia" , "Ebrima"  , "Corbel, Arial , Bahnschrift                 

font_family <- "Bahnschrift"
ggplot() +
  geom_raster(data = depth_tibble, aes(x = x, y = y, fill = bathymetry)) +
  scale_fill_distiller(guide = guide_colourbar(
        title = "Bathymetry",
        title.theme = element_text(
          size = 8, 
          face = "bold",
          family = font_family,
          hjust = 0.5),
        title.position = 'top',
        title.hjust = 0,
        ticks = FALSE,
        barwidth = unit(6, 'lines'),
        barheight = unit(0.4, 'lines'),
        label.theme = element_text(size = 6))) +
  labs(title = "Bathymetry map") +
  theme(title = element_text(family = font_family))
```


# Map of france with the study area in a rectangle

```{r}
sf_use_s2(FALSE)
france <- st_crop(
  x = world,
  xmin = -4.5,
  ymin = 41,
  xmax = 8,
  ymax = 51
) %>% 
  filter(sovereignt != "United Kingdom")

rectangle <- tibble(coord = c(2.5, 42, 6, 43.7),
                    name = c("xmin", "ymin", "xmax", "ymax")) %>% 
  pivot_wider(everything(), names_from = name, values_from = coord)

map_france <- ggplot() + geom_sf(data = france, fill= "white") +
  geom_rect(data = rectangle, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
            fill = NA, color = "red") +
  theme(panel.background = element_rect(fill = "aliceblue"),
        panel.grid = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.background = element_blank()) 

map_france
```


```{r}

contour_gdl_elev <- gdl_elev_raster %>% 
  crop(st_bbox(contour_golfe))

contour_gdl_depth <- depth_raster2 %>% 
  crop(st_bbox(contour_golfe)) 

depth_tibble2 <- crds(contour_gdl_depth) %>% 
  bind_cols(as_tibble(contour_gdl_depth))


plot_effort <- function(data_eff, color, plot_title="", plot_subtitle=""){
  ggplot() + 
    geom_raster(data = depth_tibble2, aes(x = x, y = y, fill = bathymetry)) +
    scale_fill_distiller(guide = F) +
    new_scale_fill() +
    layer_spatial(contour_gdl_elev) +
    scale_fill_gradientn(colors = terrain.colors(n = 40), 
                         na.value = 0,
                         guide = FALSE) +
    geom_sf(data = data_eff %>% st_intersection(study_area),
            color = color, linewidth = 0.3)  +
    annotation_scale(location = "br", width_hint = 0.3,
                     height = unit(0.07, "cm"),
                     text_cex = 0.4) +
    theme_classic() +
    theme(
          axis.text = element_blank(),
          axis.ticks = element_blank(),
          axis.title = element_blank(),
          axis.line = element_blank(),
          plot.title = element_text(hjust = 0.5, 
                                    size = 7, 
                                    face = "bold"),
          plot.subtitle = element_text(hjust = 0.5, 
                                    size = 5)) +
    labs(title = plot_title,
         subtitle = plot_subtitle)
}

 

p1 <- plot_effort(migralion_eff, 
                  color = "darkmagenta",
                  plot_title = "Migralion",
                  plot_subtitle = "2022-2023")

p2 <- plot_effort(pelmed_eff,
                  color = "darkblue",
                  plot_title = "Pelmed",
                  plot_subtitle = "2017-2021")

p3 <- plot_effort(samm_eff,
                  color = "darkred",
                  plot_title = "SAMM",
                  plot_subtitle = "2022-2023")


p4 <- plot_effort(pnm_eff,
                  color = "darkorange",
                  plot_title = "PNM",
                  plot_subtitle = "2019-2021") 

effort_column <- p1 + p2 + p3 + p4 +
  plot_layout(ncol = 2)

effort_column
```


```{r, fig.width=10}
(lion_gulf_plot +
  inset_element(
    map_france,
    left = 0,
    bottom = 0.6,
    right = 0.4,
    top = 0.95,
    align_to = "full"
  ) |
  effort_column) 
  # plot_layout(widths = unit(c(12, 8), "cm"))
```




