---
title: "Model comparison"
author: "Louis Schroll"
date: "2024-04-18"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loading}
# load package
library(tidyverse, warn.conflicts = FALSE)
library(sf)
library(nimble, warn.conflicts = FALSE)
library(patchwork)
# library(extrafont)

local_path <- "~/stage_M2/"
# load functions
path_to_Rfunc <- paste0(local_path, "2.code/pt2_telemetry_and_count/R_func")
sapply(paste0(path_to_Rfunc, "/", list.files(path_to_Rfunc)), source)

# load data
load(paste0(local_path, "1.data/all_seabirds_counts.rdata"))
load(paste0(local_path, "1.data/grid_cells.rdata"))
load(paste0(local_path, "1.data/RSF_data_scopoli_shearwaters.rdata"))
```

```{r}
best_cov <- list(
  goeland_leucophee_HR = c(
    "log_dist_to_shore",
    "log_bathymetry",
    "mean_winter_SST",
    "mean_spring_SST",
    "mean_summer_SST",
    "mean_autumn_SST"
  ),
  goeland_leucophee_R = c(
    "log_dist_to_shore",
    "mean_winter_SST",
    "mean_summer_SST",
    "mean_autumn_SST"
  ),
  
  petit_puffin_HR = c("log_dist_to_shore","log_bathymetry",'mean_CHL',"sd_SAL","mean_SSH"),
  petit_puffin_R = c("mean_CHL", "mean_SSH"),
  
  puffin_de_scopoli_R = c("log_mean_CHL", "sd_SAL", "mean_SSH", "sd_SSH"),
  
  sterne_caugek_HR = c(
    "mean_CHL","mean_SSH","mean_winter_SST","mean_spring_SST",
    "mean_summer_SST"
  ),
  sterne_caugek_R = c(
    "log_bathymetry",
    "mean_CHL",
    "mean_SSH",
    "sd_SSH",
    "log_sd_VEL"
  )
)
```


# Scopoli shearwater

```{r load scopoli data}
species <- "puffin_de_scopoli_R"
load(paste0(local_path, "3.results/mcmc_outputs/mcmc_output_", species,".rdata"))
load(paste0(local_path, "3.results/spOccupancy_outputs/spOccupancy_", species,".RData"))
load(paste0(local_path, "3.results/grid_spOccupancy_results.RData"))

selected_cov <- best_cov[[species]]

samples_spOcc <- model_result$beta.samples

# Load predictions
load(file = paste0(local_path, "3.results/prediction_grid/grid_", species, ".rdata")) #grid_nmix, grid_RSF, grid_int
```


```{r plot maps}
# Plot all the maps
# 0/3 spOccupancy 
grid_scopoli <- spOccupancy_res_grid %>% 
  select(grid_c, mean_psi_puffin_de_scopoli_R, sd_psi_puffin_de_scopoli_R)
names(grid_scopoli) <- c("mean_psi", "sd_psi", "grid_c")
plots_spOccupancy <- plot_prediction(grid_scopoli, plot_title = "Occupancy")
# 1/3 - N-mixture
plots_nmix <- plot_prediction(grid_nmix, plot_title = "N-mixture")
# 2/3 - RSF
plots_rsf <- plot_prediction(grid_RSF, plot_title = "RSF")
plots_rsf_mean <- plots_rsf$mean_psi_plot
# 3/3 - RSF & N-mixture
plots_int <- plot_prediction(grid_int, 
                             add_colonies = F, 
                             plot_title = "Integrated model")

```



```{r figure scopoli, fig.width=10, fig.height=10}
predictive_maps <- (plots_spOccupancy$mean_psi_plot + plots_spOccupancy$sd_psi_plot) /
  (plots_rsf_mean + plots_rsf$sd_psi_plot) /
  (plots_nmix$mean_psi_plot + plots_nmix$sd_psi_plot) /
  (plots_int$mean_psi_plot + plots_int$sd_psi_plot) +
  plot_layout(guides = "collect") +
  plot_annotation(
    theme = theme(
      legend.position = "bottom", 
      legend.spacing.x = unit(3, "cm")
    )
  ) 
coeff_df <- gather_coeff_values(sampleNmixture, 
                                samplesRSF, 
                                samplesint, 
                                samples_spOcc, 
                                selected_cov)

sal_plot <- plot_coeff_by_model(coeff_df, 
                    covariate_name = "sd_sal", 
                    plot_title = "Salinity variability", 
                    plot_subtitle = "(standard deviation)")

sd_ssh_plot <- plot_coeff_by_model(coeff_df, 
                    covariate_name = "sd_ssh", 
                    plot_title = "SSH variability", 
                    plot_subtitle = "(standard deviation)")

mean_ssh_plot <- plot_coeff_by_model(coeff_df, 
                                covariate_name = "mean_ssh", 
                                plot_title = "Sea Surface Height", 
                                plot_subtitle = "(SSH)")

chl_plot <- plot_coeff_by_model(coeff_df, 
                                covariate_name = "log_mean_chl", 
                                plot_title = "Chlorophyl A", 
                                plot_subtitle = "(log)")

coefficient_plot <- (sd_ssh_plot + sal_plot + mean_ssh_plot + chl_plot) +
  plot_layout(guides = "collect", tag_level = "new") + 
  plot_annotation(
    theme = theme(
      legend.position = "bottom",
      legend.text = element_text(
        #family  = "Arial",
        face = "bold",
        size = 9
      )))

precision_plot <- plot_space_use_precision(grid_nmix = grid_nmix, 
                         grid_RSF = grid_RSF, 
                         grid_int = grid_int, 
                         grid_spOcc = grid_scopoli)

plot_left <- (coefficient_plot / precision_plot) +
  plot_layout(heights = c(7, 4))

(predictive_maps | plot_left) +
  plot_layout(
    guide = "collect"
  ) +
  plot_annotation(
    title = "Scopoli shearwater space-use",
    #caption = 'Source: Migralion project & PELMED 2017-2021',
    theme = theme(
      plot.title = element_text(size = 15, face = "bold", hjust = 0.5),
      legend.position = 'top'
    )
  )
```

# Sandwich tern

## Repro

```{r load caugek data}
species <- "sterne_caugek_R"
load(paste0(local_path, "3.results/mcmc_outputs/mcmc_output_", species,".rdata"))
load(paste0(local_path, "3.results/spOccupancy_outputs/spOccupancy_", species,".RData"))
samples_spOcc <- model_result$beta.samples
load(paste0(local_path, "3.results/grid_spOccupancy_results.RData"))

selected_cov <- best_cov[[species]]

#samples_spOcc <- model_result$beta.samples

# Load predictions
load(file = paste0(local_path, "3.results/prediction_grid/grid_", species, ".rdata"))
```


```{r plot maps}
# Plot all the maps
# 0/3 spOccupancy 
grid_caugek_R <- spOccupancy_res_grid %>% 
  select(grid_c, mean_psi_sterne_caugek_R, sd_psi_sterne_caugek_R)
names(grid_caugek_R) <- c("mean_psi", "sd_psi", "grid_c")
plots_spOccupancy <- plot_prediction(grid_caugek_R, plot_title = "Occupancy", legend_position = "none")
# 1/3 - N-mixture
plots_nmix <- plot_prediction(grid_nmix, plot_title = "N-mixture")
# 2/3 - RSF
plots_rsf <- plot_prediction(grid_RSF, plot_title = "RSF")
plots_rsf_mean <- plots_rsf$mean_psi_plot
# 3/3 - RSF & N-mixture
plots_int <- plot_prediction(grid_int, 
                             add_colonies = F, 
                             plot_title = "Integrated model")

```



```{r figure scopoli, fig.width=10, fig.height=10}
predictive_maps <- 
  (plots_spOccupancy$mean_psi_plot + plots_spOccupancy$sd_psi_plot) /
  (plots_rsf_mean + plots_rsf$sd_psi_plot) /
  (plots_nmix$mean_psi_plot + plots_nmix$sd_psi_plot) /
  (plots_int$mean_psi_plot + plots_int$sd_psi_plot) +
  plot_layout(guides = "collect", nrow = 4) +
  plot_annotation(
    theme = theme(
      legend.position = "bottom", 
      legend.spacing.x = unit(3, "cm")
    )
  )

coefficient_plot <- gather_coeff_values(sampleNmixture = sampleNmixture, 
                                        samples_spOcc = samples_spOcc, 
                                        samplesRSF = samplesRSF, 
                                        samplesint = samplesint,
                                        selected_cov = selected_cov) %>%  
  change_covariate_names() %>% 
  plot_coeff_by_model2(ncol = 2)

precision_plot <- plot_space_use_precision(grid_nmix = grid_nmix, 
                         grid_RSF = grid_RSF, 
                         grid_int = grid_int, 
                         grid_spOcc = grid_caugek_R)

plot_left <- (coefficient_plot / precision_plot) +
  plot_layout(heights = c(7, 4))

(predictive_maps | plot_left) +
  plot_layout(
    guide = "keep"
  ) +
  plot_annotation(
    title = "Sandwich tern space-use (Summer)",
    #caption = 'Source: Migralion project & PELMED 2017-2021',
    theme = theme(
      plot.title = element_text(size = 15, face = "bold", hjust = 0.5),
      legend.position = 'top'
    )
  )
```


```{r figure scopoli, fig.width=10, fig.height=10}
load(paste0(local_path, "1.data/RSF_data_sandwich_tern.rdata"))
df_RSF <- df_RSF %>% filter(month %in% 4:8)
plots_rsf_mean +
  (ggplot() + geom_point(data = df_RSF %>% filter(case==1), aes(x=X, y=Y), alpha = 0.1)) +
    geom_sf(data = contour_golfe, color = "black", fill = "antiquewhite") 
```



## Hors repro

```{r load scopoli data}
species <- "sterne_caugek_HR"
load(paste0(local_path, "3.results/mcmc_outputs/mcmc_output_", species,".rdata"))
load(paste0(local_path, "3.results/spOccupancy_outputs/spOccupancy_", species,".RData"))
load(paste0(local_path, "3.results/grid_spOccupancy_results.RData"))

selected_cov <- best_cov[[species]]

samples_spOcc <- model_result$beta.samples

# Make predictions
grid_nmix <- make_prediction(samplesNmixture, grid, selected_cov)
grid_RSF <- make_prediction(samplesRSF, grid, selected_cov, include_intercept = F, rsf_intercept = "beta_pop[1]")
grid_int <- make_prediction(samplesint, 
                            grid, 
                            selected_cov, 
                            rsf_intercept = "beta_pop[1]")
```


```{r plot maps}
# Plot all the maps
# 0/3 spOccupancy 
grid_caugek_R <- spOccupancy_res_grid %>% 
  select(grid_c, mean_psi_sterne_caugek_R, sd_psi_sterne_caugek_R)
names(grid_caugek_R) <- c("mean_psi", "sd_psi", "grid_c")
plots_spOccupancy <- plot_occupancy(grid_caugek_R, plot_title = "Occupancy")
# 1/3 - N-mixture
plots_nmix <- plot_prediction(grid_nmix, plot_title = "N-mixture")
# 2/3 - RSF
plots_rsf <- plot_prediction(grid_RSF, plot_title = "RSF")
plots_rsf_mean <- plots_rsf$mean_psi_plot
# 3/3 - RSF & N-mixture
plots_int <- plot_prediction(grid_int, 
                             add_colonies = F, 
                             plot_title = "Integrated model")

```



```{r figure scopoli, fig.width=10, fig.height=10}
predictive_maps <- (plots_spOccupancy$mean_psi_plot + plots_spOccupancy$sd_psi_plot) /
  ((plots_rsf_mean + plots_rsf$sd_psi_plot) /
  (plots_nmix$mean_psi_plot + plots_nmix$sd_psi_plot) /
  (plots_int$mean_psi_plot + plots_int$sd_psi_plot) +
  plot_layout(guides = "collect") +
  plot_annotation(
    title = '',
    #caption = 'Source: Migralion project & PELMED 2017-2021',
    theme = theme(
      plot.title = element_text(size = 20,
                                face = "bold",
                                hjust = 0.5),
      legend.position = "bottom", 
    )
  )) +
  plot_layout(heights = c(1, 3.8))


coefficient_plot <- gather_coeff_values(sampleNmixture = sampleNmixture, 
                                        samples_spOcc = samples_spOcc, 
                                        samplesRSF = samplesRSF, 
                                        samplesint = samplesint,
                                        selected_cov = selected_cov) %>%  
  change_covariate_names() %>% 
  plot_coeff_by_model2()

precision_plot <- plot_space_use_precision(grid_nmix = grid_nmix, 
                         grid_RSF = grid_nmix, 
                         grid_int = grid_int, 
                         grid_spOcc = grid_scopoli)

plot_left <- (coefficient_plot / precision_plot) +
  plot_layout(heights = c(7, 4))

(predictive_maps | plot_left) +
  plot_layout(
    guide = "keep"
  ) +
  plot_annotation(
    title = "Scopoli shearwater space-use",
    #caption = 'Source: Migralion project & PELMED 2017-2021',
    theme = theme(
      plot.title = element_text(size = 15, face = "bold", hjust = 0.5),
      legend.position = 'top'
    )
  )
```


```{r figure scopoli, fig.width=10, fig.height=10}
load(paste0(local_path, "1.data/RSF_data_sandwich_tern.rdata"))
df_RSF <- df_RSF %>% filter(month %in% 4:8)
plots_rsf_mean +
  (ggplot() + geom_point(data = df_RSF %>% filter(case==1), aes(x=X, y=Y), alpha = 0.1) +
    geom_sf(data = contour_golfe, color = "black", fill = "antiquewhite") +
    theme_bw())
```


# Goeland leucophee
## Hors repro

```{r load scopoli data}
species <- "goeland_leucophee_HR"
load(paste0(local_path, "3.results/mcmc_outputs/mcmc_output_", species,".rdata"))
load(paste0(local_path, "3.results/spOccupancy_outputs/spOccupancy_", species,".RData"))
load(paste0(local_path, "3.results/grid_spOccupancy_results.RData"))

selected_cov <- best_cov[[species]]

samples_spOcc <- model_result$beta.samples

# Make predictions
grid_nmix <- make_prediction(samplesNmixture, grid, selected_cov)
grid_RSF <- make_prediction(samplesRSF, grid, selected_cov, include_intercept = F, rsf_intercept = "beta_pop[1]")
grid_int <- make_prediction(samplesint, 
                            grid, 
                            selected_cov, 
                            rsf_intercept = "beta_pop[1]")
```


```{r plot maps}
# Plot all the maps
# 0/3 spOccupancy 
grid_caugek_R <- spOccupancy_res_grid %>% 
  select(grid_c, mean_psi_goeland_leucophee_HR, sd_psi_goeland_leucophee_HR)
names(grid_caugek_R) <- c("mean_psi", "sd_psi", "grid_c")
plots_spOccupancy <- plot_occupancy(grid_caugek_R, plot_title = "Occupancy")
# 1/3 - N-mixture
plots_nmix <- plot_prediction(grid_nmix, plot_title = "N-mixture")
# 2/3 - RSF
plots_rsf <- plot_prediction(grid_RSF, plot_title = "RSF")
plots_rsf_mean <- plots_rsf$mean_psi_plot
# 3/3 - RSF & N-mixture
plots_int <- plot_prediction(grid_int, 
                             add_colonies = F, 
                             plot_title = "Integrated model")

```



```{r figure scopoli, fig.width=10, fig.height=10}
predictive_maps <- (plots_spOccupancy$mean_psi_plot + plots_spOccupancy$sd_psi_plot) /
  ((plots_rsf_mean + plots_rsf$sd_psi_plot) /
  (plots_nmix$mean_psi_plot + plots_nmix$sd_psi_plot) /
  (plots_int$mean_psi_plot + plots_int$sd_psi_plot) +
  plot_layout(guides = "collect") +
  plot_annotation(
    title = '',
    #caption = 'Source: Migralion project & PELMED 2017-2021',
    theme = theme(
      plot.title = element_text(size = 20,
                                face = "bold",
                                hjust = 0.5),
      legend.position = "bottom", 
    )
  )) +
  plot_layout(heights = c(1, 3.8))


coefficient_plot <- gather_coeff_values(sampleNmixture = sampleNmixture, 
                                        samples_spOcc = samples_spOcc, 
                                        samplesRSF = samplesRSF, 
                                        samplesint = samplesint,
                                        selected_cov = selected_cov) %>%  
  change_covariate_names() %>% 
  plot_coeff_by_model2()

precision_plot <- plot_space_use_precision(grid_nmix = grid_nmix, 
                         grid_RSF = grid_nmix, 
                         grid_int = grid_int, 
                         grid_spOcc = grid_scopoli)

plot_left <- (coefficient_plot / precision_plot) +
  plot_layout(heights = c(7, 4))

(predictive_maps | plot_left) +
  plot_layout(
    guide = "keep"
  ) +
  plot_annotation(
    title = "Scopoli shearwater space-use",
    #caption = 'Source: Migralion project & PELMED 2017-2021',
    theme = theme(
      plot.title = element_text(size = 15, face = "bold", hjust = 0.5),
      legend.position = 'top'
    )
  )
```


```{r figure scopoli, fig.width=10, fig.height=10}
load(paste0(local_path, "1.data/RSF_data_yellow_legged_gull.rdata"))
df_RSF <- df_RSF %>% filter(month %in% c(1:3, 9:12))
plots_rsf_mean +
  (ggplot() + geom_point(data = df_RSF %>% filter(case==1), aes(x=X, y=Y), alpha = 0.1) +
    geom_sf(data = contour_golfe, color = "black", fill = "antiquewhite") +
    theme_bw())
```