---
title: "RSF"
author: "Louis Schroll"
date: "2024-05-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
```


```{r loading}
# load package
library(tidyverse, warn.conflicts = FALSE)
library(sf)
library(nimble, warn.conflicts = FALSE)
library(patchwork)
# library(extrafont)

local_path <- "~/stage_M2/"

# load data
load(paste0(local_path, "1.data/all_seabirds_counts.rdata"))
load(paste0(local_path, "1.data/grid_cells.rdata"))
load(paste0(local_path, "1.data/RSF_data_scopoli_shearwaters.rdata"))
load(paste0(local_path, "1.data/all_seabirds_counts.rdata"))

# load functions
path_to_Rfunc <- paste0(local_path, "2.code/pt2_telemetry_and_count/R_func")
sapply(paste0(path_to_Rfunc, "/", list.files(path_to_Rfunc)), source)
```

```{r}
best_cov <- list(
  goeland_leucophee_HR = c(
    "log_dist_to_shore",
    "log_bathymetry",
    "mean_winter_SST",
    "mean_spring_SST",
    "mean_summer_SST",
    "mean_autumn_SST"
  ),
  goeland_leucophee_R = c(
    "log_dist_to_shore",
    "mean_winter_SST",
    "mean_summer_SST",
    "mean_autumn_SST"
  ),
  
  petit_puffin_HR = c("log_dist_to_shore","log_bathymetry",'mean_CHL',"sd_SAL","mean_SSH"),
  petit_puffin_R = c("mean_CHL", "mean_SSH"),
  
  puffin_de_scopoli_R = c("log_mean_CHL", "sd_SAL", "mean_SSH", "sd_SSH"),
  
  sterne_caugek_HR = c(
    "mean_CHL","mean_SSH","mean_winter_SST","mean_spring_SST",
    "mean_summer_SST"
  ),
  sterne_caugek_R = c(
    "log_bathymetry",
    "mean_CHL",
    "mean_SSH",
    "sd_SSH",
    "log_sd_VEL"
  )
)

month_to_keep <- list(
  goeland_leucophee_HR = c(1:3, 9:12),
  goeland_leucophee_R = 4:8,
  
  petit_puffin_HR = c(1:3, 9:12),
  petit_puffin_R = 4:8,
  
  puffin_de_scopoli_R = 1:12,
  
  sterne_caugek_HR = c(1:3, 9:12),
  sterne_caugek_R = 4:8
)

```

# Scopoli shearwater

```{r}
species <- "puffin_de_scopoli_R"
load(paste0(local_path, "3.results/mcmc_outputs/mcmc_output_", species,".rdata"))

selected_cov <- best_cov[[species]]

# Make predictions
grid_RSF <- make_prediction(mcmc.output = samplesRSF, 
                            grid, 
                            selected_cov, 
                            include_intercept = F, 
                            rsf_intercept = "beta_pop[1]")

plots_rsf <- plot_prediction(grid_RSF, plot_title = "RSF")
plots_rsf_mean <- plots_rsf$mean_psi_plot

load(paste0(local_path, "1.data/RSF_data_scopoli_shearwaters.rdata"))
df_RSF <- df_RSF %>% filter(month %in% 4:8)

plots_rsf_mean 
plots_rsf$sd_psi_plot
ggplot() + 
  geom_point(data = df_RSF %>% filter(case==1), 
             aes(x=X, y=Y, color = as.factor(individual_id)), 
             alpha = 0.1) +
  geom_sf(data = contour_golfe, color = "black", fill = "antiquewhite")+
  theme_bw() +
  theme(legend.position = "none") 

mcmcplots::traplot(samplesRSF)
mcmcplots::denplot(samplesRSF)

MCMCvis::MCMCsummary(samplesRSF) %>% knitr::kable()

df_RSF %>% 
  as_tibble() %>% 
  select(all_of(selected_cov), case) %>% 
  pivot_longer(-case, names_to = "cov") %>% 
  ggplot(aes(y=value, x = as.factor(case))) +
  facet_wrap(~~factor(cov, levels=selected_cov)) +
  geom_boxplot() +
  theme_bw() +
  labs(title = "Mean value used / available habitat")

MCMCvis::MCMCplot(samplesRSF, params = "beta_pop")

grid_RSF$mean_psi
```


# Caugek repro

```{r}
species <- "sterne_caugek_R"
load(paste0(local_path, "3.results/mcmc_outputs/mcmc_output_", species,".rdata"))

selected_cov <- best_cov[[species]]

# Make predictions
grid_RSF <- make_prediction(samplesRSF, grid, selected_cov, include_intercept = F, rsf_intercept = "beta_pop[1]")

plots_rsf <- plot_prediction(grid_RSF, plot_title = "RSF")
plots_rsf_mean <- plots_rsf$mean_psi_plot

load(paste0(local_path, "1.data/RSF_data_sandwich_tern.rdata"))
df_RSF <- df_RSF %>% filter(month %in% 4:8)

plots_rsf_mean 
plots_rsf$sd_psi_plot
ggplot() + 
  geom_point(data = df_RSF %>% filter(case==1), 
             aes(x=X, y=Y), alpha = 0.1) +
  geom_sf(data = contour_golfe, color = "black", fill = "antiquewhite") 

mcmcplots::traplot(samplesRSF)
mcmcplots::denplot(samplesRSF)

MCMCvis::MCMCsummary(samplesRSF) %>% knitr::kable()
```

```{r}
df_RSF %>% 
  as_tibble() %>% 
  select(all_of(selected_cov), case) %>% 
  pivot_longer(-case, names_to = "cov") %>% 
  ggplot(aes(y=value, x = as.factor(case))) +
  facet_wrap(~~factor(cov, levels=selected_cov)) +
  geom_boxplot() +
  theme_bw() +
  labs(title = "Mean value used / available habitat")

MCMCvis::MCMCplot(samplesRSF, params = "beta_pop")
```




# Caugek hors repro

```{r}
species <- "sterne_caugek_HR"
load(paste0(local_path, "3.results/mcmc_outputs/mcmc_output_", species,".rdata"))

selected_cov <- best_cov[[species]]

# Make predictions
grid_RSF <- make_prediction(samplesRSF, grid, selected_cov, include_intercept = F, rsf_intercept = "beta_pop[1]")

plots_rsf <- plot_prediction(grid_RSF, plot_title = "RSF")
plots_rsf_mean <- plots_rsf$mean_psi_plot

load(paste0(local_path, "1.data/RSF_data_sandwich_tern.rdata"))
df_RSF <- df_RSF %>% filter(month %in% month_to_keep[[species]])

plots_rsf_mean 
plots_rsf$sd_psi_plot
ggplot() + 
  geom_point(data = df_RSF %>% filter(case==1), aes(x=X, y=Y), alpha = 0.1) +
  geom_sf(data = contour_golfe, color = "black", fill = "antiquewhite") 

mcmcplots::traplot(samplesRSF)
mcmcplots::denplot(samplesRSF)

MCMCvis::MCMCsummary(samplesRSF) %>% knitr::kable()

df_RSF %>% 
  as_tibble() %>% 
  select(all_of(selected_cov), case) %>% 
  pivot_longer(-case, names_to = "cov") %>% 
  ggplot(aes(y=value, x = as.factor(case))) +
  facet_wrap(~~factor(cov, levels=selected_cov)) +
  geom_boxplot() +
  theme_bw() +
  labs(title = "Mean value used / available habitat")

MCMCvis::MCMCplot(samplesRSF, params = "beta_pop")
```


# Leucophee repro

```{r}
species <- "goeland_leucophee_R"
load(paste0(local_path, "3.results/mcmc_outputs/mcmc_output_", species,".rdata"))

selected_cov <- best_cov[[species]]

# Make predictions
grid_RSF <- make_prediction(samplesRSF, grid, selected_cov, include_intercept = F, rsf_intercept = "beta_pop[1]")

plots_rsf <- plot_prediction(grid_RSF, plot_title = "RSF")
plots_rsf_mean <- plots_rsf$mean_psi_plot

load(paste0(local_path, "1.data/RSF_data_yellow_legged_gull.rdata"))
df_RSF <- df_RSF %>% filter(month %in% month_to_keep[[species]])

plots_rsf_mean 
plots_rsf$sd_psi_plot
ggplot() + 
  geom_point(data = df_RSF %>% filter(case==1), aes(x=X, y=Y), alpha = 0.1) +
  geom_sf(data = contour_golfe, color = "black", fill = "antiquewhite") 

mcmcplots::traplot(samplesRSF)
mcmcplots::denplot(samplesRSF)

MCMCvis::MCMCsummary(samplesRSF) %>% knitr::kable()

df_RSF %>% 
  as_tibble() %>% 
  select(all_of(selected_cov), case) %>% 
  pivot_longer(-case, names_to = "cov") %>% 
  ggplot(aes(y=value, x = as.factor(case))) +
  facet_wrap(~~factor(cov, levels=selected_cov)) +
  geom_boxplot() +
  theme_bw() +
  labs(title = "Mean value used / available habitat")

MCMCvis::MCMCplot(samplesRSF, params = "beta_pop")
```


# Leucophee hors repro

```{r}
species <- "goeland_leucophee_HR"
load(paste0(local_path, "3.results/mcmc_outputs/mcmc_output_", species,".rdata"))

selected_cov <- best_cov[[species]]

# Make predictions
grid_RSF <- make_prediction(samplesRSF, grid, selected_cov, include_intercept = F, rsf_intercept = "beta_pop[1]")

plots_rsf <- plot_prediction(grid_RSF, plot_title = "RSF")
plots_rsf_mean <- plots_rsf$mean_psi_plot

load(paste0(local_path, "1.data/RSF_data_yellow_legged_gull.rdata"))
df_RSF <- df_RSF %>% filter(month %in% month_to_keep[[species]])

plots_rsf_mean 
plots_rsf$sd_psi_plot
ggplot() + 
  geom_point(data = df_RSF %>% filter(case==1), aes(x=X, y=Y), alpha = 0.1) +
  geom_sf(data = contour_golfe, color = "black", fill = "antiquewhite") 

mcmcplots::traplot(samplesRSF)
mcmcplots::denplot(samplesRSF)

MCMCvis::MCMCsummary(samplesRSF) %>% knitr::kable()

df_RSF %>% 
  as_tibble() %>% 
  select(all_of(selected_cov), case) %>% 
  pivot_longer(-case, names_to = "cov") %>% 
  ggplot(aes(y=value, x = as.factor(case))) +
  facet_wrap(~~factor(cov, levels=selected_cov)) +
  geom_boxplot() +
  theme_bw() +
  labs(title = "Mean value used / available habitat")

MCMCvis::MCMCplot(samplesRSF, params = "beta_pop")
```


# yelkouan repro

```{r}
species <- "petit_puffin_R"
load(paste0(local_path, "3.results/mcmc_outputs/mcmc_output_", species,".rdata"))

selected_cov <- best_cov[[species]]

# Make predictions
grid_RSF <- make_prediction(samplesRSF, grid, selected_cov, include_intercept = F, rsf_intercept = "beta_pop[1]")

plots_rsf <- plot_prediction(grid_RSF, plot_title = "RSF")
plots_rsf_mean <- plots_rsf$mean_psi_plot

load(paste0(local_path, "1.data/RSF_puffin_yelkouan.rdata"))
df_RSF <- df_RSF %>% filter(month %in% month_to_keep[[species]])

plots_rsf_mean 
plots_rsf$sd_psi_plot
ggplot() + 
  geom_point(data = df_RSF %>% filter(case==1), aes(x=X, y=Y), alpha = 0.1) +
  geom_sf(data = contour_golfe, color = "black", fill = "antiquewhite") 

mcmcplots::traplot(samplesRSF)
mcmcplots::denplot(samplesRSF)

MCMCvis::MCMCsummary(samplesRSF) %>% knitr::kable()

df_RSF %>% 
  as_tibble() %>% 
  select(all_of(selected_cov), case) %>% 
  pivot_longer(-case, names_to = "cov") %>% 
  ggplot(aes(y=value, x = as.factor(case))) +
  facet_wrap(~~factor(cov, levels=selected_cov)) +
  geom_boxplot()

MCMCvis::MCMCplot(samplesRSF, params = "beta_pop")
```

# yelkouan repro

```{r}
species <- "petit_puffin_HR"
load(paste0(local_path, "3.results/mcmc_outputs/mcmc_output_", species,".rdata"))

selected_cov <- best_cov[[species]]

# Make predictions
grid_RSF <- make_prediction(samplesRSF, grid, selected_cov, include_intercept = F, rsf_intercept = "beta_pop[1]")

plots_rsf <- plot_prediction(grid_RSF, plot_title = "RSF")
plots_rsf_mean <- plots_rsf$mean_psi_plot

load(paste0(local_path, "1.data/RSF_puffin_yelkouan.rdata"))
df_RSF <- df_RSF %>% filter(month %in% month_to_keep[[species]])

plots_rsf_mean 
plots_rsf$sd_psi_plot
ggplot() + 
  geom_point(data = df_RSF %>% filter(case==1), aes(x=X, y=Y), alpha = 0.1) +
  geom_sf(data = contour_golfe, color = "black", fill = "antiquewhite") 

mcmcplots::traplot(samplesRSF)
mcmcplots::denplot(samplesRSF)

MCMCvis::MCMCsummary(samplesRSF) %>% knitr::kable()

df_RSF %>% 
  as_tibble() %>% 
  select(all_of(selected_cov), case) %>% 
  pivot_longer(-case, names_to = "cov") %>% 
  ggplot(aes(y=value, x = as.factor(case))) +
  facet_wrap(~~factor(cov, levels=selected_cov)) +
  geom_boxplot()

MCMCvis::MCMCplot(samplesRSF, params = "beta_pop")
```




